#配置端口
server:
  port: 8888

spring:
  # 配置数据源
  datasource:
    # 配置数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/epacms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 集成redis
  redis:
    host: 47.102.202.189
    port: 6379
    database: 0 #reids 数据库索引默认为 0
    password:   #密码默认为空
    lettuce:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 2000
  data:
    redis:
      repositories:
        # redis 只用作缓存，不作为 repository
        enabled: false
  # 整合邮件配置
  mail:
    # 编码集
    default-encoding: UTF-8
    # smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.qq.com
    # 服务协议 smtp为发送邮件
    protocol: smtp
    # 发送邮件的账户
    username: 302920276@qq.com
    # 授权码 邮箱服务器提供的授权码，不是你邮箱的密码
    password: twgyskxatdgucbdi
    #开启一些权限
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
    port: 465
  main:
    allow-circular-references: true

mybatis-plus:
  configuration:
    # 配置mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

uploadFile:
  path: /Users/chenya/Desktop/upload/ #自定义文件上传路径

jwt:
  # Jwt存储的请求头
  tokenHeader: Authorization
  # Jwt加密秘钥
  secret: epacms-*-secret
  # Jwt 的超期限时间（60*60）*24 * 7
  expiration: 604800
  # Jwt负载中拿到开头
  tokenHead: Bearer


